export const workorderTypes = {
  "On Demand": "primary",
  Project: "secondary",
  Emergency: "error",
  Warranty: "success",
  "Back Charge": "warning",
};

export const workorderStatuses = {
  New: "primary",
  Sourcing: "warning",
  Sourced: "info",
  Scheduled: "success",
  "In Progress": "warning",
  Completed: "success",
  Reopened: "error",
  Cancelled: "error",
  "Requires proposal": "warning",
  "Waiting approval": "warning",
  "Proposal Approved": "success",
};

export const mappedStatuses = {
  New: "New",
  Sourcing: "Accepted",
  Sourced: "Accepted",
  Scheduled: "Scheduled",
  "In Progress": "In Progress",
  Completed: "Completed",
  Reopened: "Reopened",
  Cancelled: "Cancelled",
  "Requires proposal": "Requires proposal",
  "Waiting approval": "Waiting approval",
  "Proposal Approved": "Proposal Approved",
};

export const clientStatusArray = {
  New: "primary",
  Accepted: "info",
  Scheduled: "warning",
  "In Progress": "warning",
  Completed: "success",
  Reopened: "error",
  Cancelled: "error",
  "Requires proposal": "warning",
  "Waiting approval": "warning",
  "Proposal Approved": "success",
};

export const trades = [
  { id: 5, name: "Asphalt" },
  { id: 6, name: "Backflow Testing" },
  { id: 40, name: "Civil Construction" },
  { id: 7, name: "Canopy Repair" },
  { id: 8, name: "Carpentry" },
  { id: 9, name: "Compactors" },
  { id: 44, name: "Deicing" },
  { id: 10, name: "Dish Machine" },
  { id: 11, name: "Doors - Automatic" },
  { id: 12, name: "Doors - Standard" },
  { id: 13, name: "Electrical" },
  { id: 14, name: "Fire Safety" },
  { id: 15, name: "Flooring" },
  { id: 16, name: "Glass Repair" },
  { id: 17, name: "Graffiti" },
  { id: 18, name: "Grease Trap" },
  { id: 19, name: "Gutters" },
  { id: 21, name: "Handyman Services" },
  { id: 22, name: "Hoods" },
  { id: 20, name: "HVAC" },
  { id: 23, name: "Ice Machines" },
  { id: 24, name: "Irrigation" },
  { id: 1, name: "Janitorial" },
  { id: 4, name: "Landscaping" },
  { id: 25, name: "Locks" },
  { id: 3, name: "Lot Sweeping" },
  { id: 26, name: "Masonry / Concrete" },
  { id: 27, name: "Painting" },
  { id: 28, name: "Pest Control" },
  { id: 29, name: "Plumbing" },
  { id: 30, name: "Pressure Washing" },
  { id: 31, name: "Refrigeration" },
  { id: 32, name: "Restaurant Equipment" },
  { id: 33, name: "Roofing" },
  { id: 34, name: "Security" },
  { id: 35, name: "Siding" },
  { id: 2, name: "Snow" },
  { id: 41, name: "Snow Hauling" },
  { id: 42, name: "Snow Plowing" },
  { id: 43, name: "Snow Shoveling" },
  { id: 36, name: "Signage" },
  { id: 37, name: "Storefront Repairs" },
  { id: 38, name: "Water Mitigation" },
  { id: 39, name: "Welding" },
  { id: 45, name: "Other" },
];
